# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dependencies:
    runs-on: git-runner
    steps:
      - uses: actions/checkout@v3
      - name: Installing_dependencies
      - run: bash dependencies.sh
  
  build:
    runs-on: git-runner
    steps:
     - run: cd /home/ubuntu
     - run: npm -f install
    # - run: npm test
     - run: cd /home/ubuntu
     - run: pm2 -f start server.js

